export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const REQUEST_SESSION = 'REQUEST_SESSION';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_TEXT = "SEARCH_TEXT";
export const SET_SESSION = 'SET_SESSION';
